### PR TITLE
add entry for ConcourseDB

### PR DESCRIPTION
**Pull request by jtnelson**

### CODE REVIEW

**Comment by edlich** [comment]
Dear jtnelson, your pull request contains >1600 lines and several 100 lines of changes that are not related to ConcourseDB. Please talk to me at edlich@gmail.com. What category it your DB? Best Regards
Stefan E.

**Comment by ipf** [comment]
@edlich guess @jtnelson just removed some unnecessary whitespace that are not important for the ConcourseDB entry. Maybe he can simply change the pr to contain the important lines for ConcourseDB

**Comment by edlich** [comment]
That would be good. Thx Ingo!

**Comment by jtnelson** [comment]
Sorry about the huge diff previously. I didn't realize my text editor had altered the whitespace of the entire file. I cleaned things up, so it should be good now.

ConcourseDB can best be described as a wide-column store.

**Comment by edlich** [comment]
No problem. Can you issue a fresh request?

**Pull request closed without merging**
