### PR TITLE
Add the UnQlite NoSQL DB

### PR DESCRIPTION
**Pull request by lucapalano**
Hi,

This commit add the UnQlite NoSQL DB to the list of DBs. It's released under the 2-Clause BSD license. For more info, please, refer to: https://unqlite.org/ for more infos.

Thanks,
Luca

### CODE REVIEW

**Comment by edlich** [comment]
What is the performance? (quite brave to put yourself before Mark Logic)

**Comment by lucapalano** [comment]
I didn't find any official benchmarks. [Here](https://dba.stackexchange.com/questions/98041/are-there-any-known-benchmarks-statistics-on-unqlite) is someone that made the same question.

**Comment by adamansky** [comment]
You can check https://github.com/pmwkaa/ioarena UnQlite is listed there

**Comment by edlich** [comment]
Cool. But I have no time to build and run the results...

**Comment by lucapalano** [comment]
@adamansky thanks. In the list of supported dbs, on the root README.md, unqlite is missing:
> Supported databases: rocksdb, leveldb, forestdb, upscaledb, lmdb, mdbx, wiredtiger, sophia, sqlite3, iowow

**Pull request merged**
